const globals = require("globals");

// Identifiers shared across the classic <script> files.
const sharedGlobals = {
    canvas: "writable",
    ctx: "writable",
    gameState: "writable",
    puzzle: "writable",
    particles: "writable",
    BOARD_WIDTH: "writable",
    BOARD_HEIGHT: "writable",
    BOARD_X: "writable",
    BOARD_Y: "writable",
    isDragging: "writable",
    draggedPiece: "writable",
    dragOffsetX: "writable",
    dragOffsetY: "writable",
    getUpgradeCost: "writable",
    getCompletionReward: "writable",
    calculatePrestigeGain: "writable",
    getAutoPlacerCost: "writable",
    getAutoSpeedCost: "writable",
    getLaunchCooldownTrack: "writable",
    loadNewPuzzleImage: "writable",
    spawnTextParticle: "writable",
    updateAndDrawParticles: "writable",
    FLAT: "writable",
    TAB: "writable",
    BLANK: "writable",
    complement: "writable",
    randomEdgeParams: "writable",
    JigsawPiece: "writable",
    generatePuzzleEdges: "writable",
    JigsawPuzzle: "writable",
    drawEdge: "writable",
    tracePiecePath: "writable",
    drawPiece: "writable",
    draw: "writable",
    recalculateBoardScale: "writable",
    resizeCanvas: "writable",
    initNewPuzzle: "writable",
    updateUI: "writable",
    buyAutoPlacer: "writable",
    buyAutoSpeed: "writable",
    upgradeDimension: "writable",
    executePrestigeReset: "writable",
    getPointerPos: "writable",
    onPointerDown: "writable",
    onPointerMove: "writable",
    onPointerUp: "writable",
    gameLoop: "writable",
    saveGame: "writable",
    loadGame: "writable",
    resetSave: "writable",
    applyOfflineProgress: "writable",
    lastSaved: "writable",
    showModal: "writable",
    showAlert: "writable",
    showConfirm: "writable",
    stats: "writable",
    lastDailyDate: "writable",
    activeSkin: "writable",
    autoStrategy: "writable",
    puzzleStartTime: "writable",
    skins: "writable",
    achievements: "writable",
    challenges: "writable",
    CHALLENGE_UNLOCK_CELLS: "writable",
    CHALLENGES: "writable",
    startChallenge: "writable",
    tickChallenges: "writable",
    buffs: "writable",
    showTutorial: "writable",
    advanceTutorial: "writable",
    finishTutorial: "writable",
    checkTutorialPopups: "writable",
    tutorialSeen: "writable",
    prestigeTipSeen: "writable",
    challengeTipSeen: "writable",
    TUTORIAL_STEPS: "writable",
    renderChallenges: "writable",
    THEMES: "writable",
    todayStr: "writable",
    recordPuzzleComplete: "writable",
    ACHIEVEMENTS: "writable",
    checkAchievements: "writable",
    renderAchievements: "writable",
    setAutoStrategy: "writable",
    tagPieceColors: "writable",
    cycleBuyAmount: "writable",
    buyAmount: "writable",
    previewCost: "writable",
    multiBuy: "writable",
    setCurrentSize: "writable",
    buySkin: "writable",
    renderSkins: "writable",
    updateAutoStrategyButtons: "writable",
    ensureAudio: "writable",
    playTone: "writable",
    playComplete: "writable",
    applyMusicSettings: "writable",
    setMusicVolume: "writable",
    toggleMute: "writable",
    toggleSfxMute: "writable",
    sfxMuted: "writable",
    runLog: "writable",
    runStartedAt: "writable",
    renderRunLog: "writable",
    musicVolume: "writable",
    musicMuted: "writable",
    localStorage: "readonly",
    location: "readonly",
    pendingImage: "writable",
    pendingLoaded: "writable",
    pendingWidth: "writable",
    pendingHeight: "writable",
    expectedImageSize: "writable",
    startImageRequest: "writable",
    preloadNextImage: "writable",
    toggleMenu: "writable",
    prestigeLevel: "writable",
    getPrestigeUpgradeCost: "writable",
    getSnapRadius: "writable",
    getHeadStartBonus: "writable",
    recomputePayoutMultiplier: "writable",
    buyPrestigeUpgrade: "writable",
};

module.exports = [
    {
        ignores: ["node_modules/**", "dist/**"],
    },
    {
        files: ["src/**/*.js"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "script",
            globals: {
                ...globals.browser,
                ...sharedGlobals,
            },
        },
        rules: {
            "no-unused-vars": "off",
            "no-undef": "error",
            eqeqeq: ["error", "always"],
            curly: ["error", "all"],
            "no-var": "error",
            "prefer-const": "error",
            indent: ["error", 4],
            quotes: ["error", "double"],
            semi: ["error", "always"],
            "comma-dangle": ["error", "always-multiline"],
        },
    },
];
